=== Petster/jpalmeri-bellevue/CSD430 - SSD/Module 9/Discussion Files/Todo.dtd
<!ELEMENT todo-list (todo-item+)>
<!ELEMENT todo-item (todo-name, todo-body)>
<!ELEMENT todo-body (todo-date, todo-content)>
<!ELEMENT todo-name (#PCDATA)>
<!ELEMENT todo-date (#PCDATA)>
<!ELEMENT todo-content (#PCDATA)>

=== Petster/jpalmeri-bellevue/CSD430 - SSD/Module 9/Discussion Files/one.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE todo-list SYSTEM "Todo.dtd">
<?xml-stylesheet type="text/css" href="styles.css"?>
<todo-list>
    <todo-item>
        <todo-name>Item 1</todo-name>
        <todo-body>
            <todo-date>10/20/2022</todo-date>
            <todo-content>Get birthday present for brother</todo-content>
        </todo-body>
    </todo-item>
    <todo-item>
        <todo-name>Item 2</todo-name>
        <todo-body>
            <todo-date>12/20/2022</todo-date>
            <todo-content>Christmas Shopping</todo-content>
        </todo-body>
    </todo-item>
    <todo-item>
        <todo-name>Item 3</todo-name>
        <todo-body>
            <todo-date>01/20/2023</todo-date>
            <todo-content>Get Ready</todo-content>
        </todo-body>
    </todo-item>
</todo-list>
